version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    links:
      - web
    ports:
      - 80:80

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    volumes:
      - postgres-data:/data
    env_file: .env

  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    command: redis-server
    volumes:
      - redis:/var/lib/redis/data

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./:/home/dockeruser/project
      - backend-modules:/usr/local/bundle
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

volumes:
  postgres-data:
  backend-modules:
  redis: